
# This is an example supabase/config.toml file.
# You can use it as a template for your own project.

# Replace the project_id with your Supabase project ID
project_id = "yjhcozddtbpzvnppcggf"

[api]
# Disables the expiration of JWTs (useful for local development when you might not access your project for days)
jwt_expiry = 3600
enable_signup = true

[auth]
# Allow email/password signups and logins
enable_signup = true
# Auto-confirm users when they sign up
disable_signup = false

[db]
# Port to run the database server on
port = 5432
# Pool mode (possible values: "transaction", "session")
pool_mode = "transaction"
