
-- Add bairro column to clients table if it doesn't exist
ALTER TABLE clients ADD COLUMN IF NOT EXISTS bairro TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS cor TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS kilometragem TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS tipo TEXT DEFAULT 'pf';
ALTER TABLE clients ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE services ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
